### ISSUE TITLE
Clear The Screen Review

### ISSUE THREAD

**Issue by Lokathor** [gfx-rs/learn-gfx-hal#5]
* **Source:** https://github.com/gfx-rs/learn-gfx-hal/blob/master/src/bin/clear_the_screen.rs
* **Explanation:** https://github.com/gfx-rs/learn-gfx-hal/blob/master/book/src/02_clear_the_window.md

This wasn't done as a branch and PR because I didn't think that _just clearing the screen_ would get this complex ;_;

However, here it is. This needs a _fine tooth comb_ level of examination.

There's some sort of bug in how it shuts down with the Vulkan backend (on Windows10) that doesn't happen with the dx12 backend. It happens even if I comment out the Drop impl entirely, so it's at least not the _ordering_ of Drop, though I could have missed something that should be destroyed but isn't.

Also, we need to examine everything that I'm saying in the text. It can be sassy and snarky, but it should not at any point be _blatantly wrong_. Unfortunately, most of what I wrote for this is just "try to parse the gfx-hal docs and the examples that I based this example off of and then write something". Some of these steps are tersely documented, and I'm not sure if that's because I don't know what should be said or if there's not much to say at the beginner's stage of things, or if there's not much to say _ever_ about the subject (because it's just plain as day).

**Comment by kvark** [comment]
Let's do a proper PR please, it's not feasible to make code comments based on a link.

**Comment by Lokathor** [comment]
alright alright made into a proper PR by commiting that it was deleted to master and then moving the files into a branch, etc etc
